AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: 'basic-messaging-service runtime infrastructure'

Parameters: 
  Service:
    Type: String
    Default: basic-messaging-service
    Description: Service Name

Resources:

  ServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Name: !Ref Service

  HelloWorldLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Service}-hello
      Description: Basic hello world to confirm development and project envrionment
      CodeUri: ../dist/api
      Handler: hello.handler
      Runtime: nodejs14.x
      Timeout: 10
      Events:
        ServiceAPI:
          Type: Api
          Properties:
            Method: get
            Path: /hello
            RestApiId: !Ref ServiceApi

  RetrieveMessagesLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Service}-retrieve
      Description: Retrieve messages for a given user
      CodeUri: ../dist/api
      Handler: retrieve.handler
      Runtime: nodejs14.x
      Timeout: 10
      Events:
        ServiceAPI:
          Type: Api
          Properties:
            Method: get
            Path: /users/{recipient}/messages
            RestApiId: !Ref ServiceApi

  SendMessagesLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Service}-send
      Description: Retrieve messages for a given user
      CodeUri: ../dist/api
      Handler: send.handler
      Runtime: nodejs14.x
      Timeout: 10
      Events:
        ServiceAPI:
          Type: Api
          Properties:
            Method: post
            Path: /users/{recipient}/messages
            RestApiId: !Ref ServiceApi
